export default [
  {
    id: 1,
    fullname: "Dr. Bamanga Ribadu",
    description: "Head of Department",
    isStaff: true,
    picture: require("./assets/faces/hod.jpg"),
    contact: {
      twitter: "https://twitter.com/aiibrahim3",
      linkedin: "https://www.linkedin.com/in/abdulrasheed-ibrahim-2b3a90103/",
      email: "mb.ribadu@googlemail.com",
      phone: "07030076860",
    },
  },
  {
    id: 1,
    fullname: "Dr. Abdullahi Bashir",
    description: "Lecturer",
    isStaff: true,
    picture: require("./assets/faces/drbashir.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "noemail",
      phone: "08034315007",
    },
  },
  {
    id: 1,
    fullname: "Dr. Suleiman Saad",
    description: "Lecturer",
    isStaff: true,
    picture: require("./assets/faces/drsaad.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "noemail",
      phone: "08033516997",
    },
  },
  {
    id: 1,
    fullname: "Mr. Kabiru Ismail",
    description: "Lecturer",
    isStaff: true,
    picture: require("./assets/faces/kabir.jpg"),
    contact: {
      twitter: "https://www.linkedin.com/in/kabir-ismail-13172567/",
      linkedin: "https://www.linkedin.com/in/kabir-ismail-13172567/",
      email: "kabir.ismail@mautech.edu.ng",
      phone: "08069251514",
    },
  },
  {
    id: 1,
    fullname: "Mr. Abdulwahab Shehu",
    description: "Exam Officer",
    isStaff: true,
    picture: require("./assets/faces/exam.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "abdulwahabshehu25@gmail.com",
      phone: "08036989864",
    },
  },
  {
    id: 1,
    fullname: "Mr. Musa Jalo",
    description: "Lecturer",
    isStaff: true,
    picture: require("./assets/faces/jalo.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "abdulwahabshehu25@gmail.com",
      phone: "08022003330",
    },
  },
  {
    id: 1,
    fullname: "Mr. Hilary Watsilla",
    description: "Lecturer",
    isStaff: true,
    picture: require("./assets/faces/hillary.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "abdulwahabshehu25@gmail.com",
      phone: "08034749701",
    },
  },
  {
    fullname: "Abdulrasheed Ibrahim",
    description: "Software Developer",
    picture: require("./assets/faces/abdul.jpg"),
    picture2: require("./assets/faces/abdoul.jpg"),
    contact: {
      twitter: "https://twitter.com/aiibrahim3",
      linkedin: "https://www.linkedin.com/in/abdulrasheed-ibrahim-2b3a90103/",
      email: "abdulrasheedibrahim47@googlemail.com",
      phone: "07033389645",
    },
  },
  {
    fullname: "Muhammad Goni Ali",
    description:
      "Two time vice Ameer And one time Ameer to the MSSN Body of the University\nMSSN Ameer to the Level through out!\nPresident to the (INAC) Interfaith Network Against Corruption Club of the university",
    picture: require("./assets/faces/amir.jpg"),
    contact: {
      twitter: "https://web.facebook.com/profile.php?id=100002105214267",
      linkedin: "",
      email: "muhammadgoniali22@gmail.com",
      phone: "08066682803",
    },
  },
  {
    fullname: "Nafiu Yau",
    description: "UI / UX",
    picture: require("./assets/faces/naf.jpg"),
    contact: {
      twitter: "https://twitter.com/NafiuYau?s=09",
      linkedin: "https://www.linkedin.com/in/nafiu-yau-901998108/",
      email: "nafiuyau27@gmail.com",
      phone: "08167295351",
    },
  },
  {
    fullname: "Muhammad Adamu Shuaibu",
    description: "System Analyst & User Interface Evaluator",
    picture: require("./assets/faces/rais.jpg"),
    contact: {
      twitter: "https://twitter.com/Muhamma78178579",
      linkedin: "https://www.linkedin.com/in/muhammad-adamu-shuaibu-b68698168/",
      email: "raizadamu@gmail.com",
      phone: "08035126805",
    },
  },
  {
    fullname: "Andy Arumse",
    description: "Software Developer",
    picture: require("./assets/faces/andy.jpg"),
    contact: {
      twitter: "https://twitter.com/alpha_malesn/",
      linkedin: "https://www.linkedin.com/in/andefikir-arumse-558aa1151/",
      email: "andyarumse1@gmail.com",
      phone: "07063169364",
    },
  },
  {
    fullname: "Usman Yau",
    description: "An entrepreneur",
    picture: require("./assets/faces/usman.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "usmanyau55@gmail.com",
      phone: "08162916606",
    },
  },
  {
    fullname: "Elisha ishaya Wasinata ",
    description: "",
    picture: require("./assets/faces/elisha.jpg"),
    contact: {
      twitter: "https://twitter.com/IshayaElisha2",
      linkedin: "https://www.linkedin.com/in/Elishaishaya",
      email: "ishayaelisha234@gmail.com",
      phone: "08134254289",
    },
  },
  {
    fullname: "Lukman babangida (Elku)",
    description: "Business man like Dangote.",
    picture: require("./assets/faces/2.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "Elku012@gmail.com",
      phone: "08033179858 ",
    },
  },
  {
    fullname: "Samuel Monday aka Linho",
    description:
      "am a young lad all the way from akwaibom state. Footballing is what I love and will always love doing.",
    picture: require("./assets/faces/1.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "samuelmonday0139@gmail.com",
      phone: "07026489381",
    },
  },
  {
    fullname: "Abubakar Zayyad Hamid",
    description:
      "I am basically a kind hearted person and quite sympathetic and sensitive. I never lose an opportunity to help my friends or anyone else. I face all situations bravely and boldly. I am optimistic and ready for any adventurous task.",
    picture: require("./assets/faces/3.jpg"),
    contact: {
      twitter: "https://twitter.com/AbubakarZayyad6",
      linkedin: "www.linkedin.com/in/abubakar-zayyad-540760216",
      email: "elkezayeed8@gmail.com",
      phone: "08143598419",
    },
  },
  {
    fullname: "Ahmed Muhammed Umar",
    description: "Social entrepreneur.",
    picture: require("./assets/faces/4.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "ahmedelrufai25@gmail.com",
      phone: "08020604501",
    },
  },
  {
    fullname: "Zakari Abdullahi",
    description:
      "Indegene of Billiri LGA of Gombe State. Popularly known as Tanko Nazuru (Autan mata).",
    picture: require("./assets/faces/5.jpg"),
    contact: {
      twitter: "https://twitter.com/ZaksAbdul",
      linkedin: "",
      email: "zaksabdul5052@gmail.com",
      phone: "07069465052/07086761066",
    },
  },
  {
    fullname: "Nazib Habibu",
    description: "",
    picture: require("./assets/faces/6.jpg"),
    contact: {
      twitter: "https://twitter.com/NazibHabibu",
      linkedin: "",
      email: "nazibhabibu@gmail.com",
      phone: "08031327151",
    },
  },
  {
    fullname: "Ngiziya Robenson (David)",
    description: "",
    picture: require("./assets/faces/7.jpg"),
    contact: {
      twitter: "https://twitter.com/david_robenson",
      linkedin: "",
      email: "ngiziya39@gmail.com",
      phone: "08069755909",
    },
  },
  {
    fullname: "Hajara isa kawu",
    description: "Hobby shopping",
    picture: require("./assets/faces/8.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "hajaralumbi@gmail.com",
      phone: "08036554191",
    },
  },
  {
    fullname: "BILYAMINU IYA",
    description: "",
    picture: require("./assets/faces/11.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "bilyaminuiya01@gmail.com",
      phone: "08086220693,08067354581",
    },
  },
  {
    fullname: "Aisha Muhammad Sheikh",
    description: "",
    picture: require("./assets/faces/12.jpg"),
    contact: {
      twitter: "",
      linkedin: "https://www.linkedin.com/in/aisha-mohammed-sheikh-311586216",
      email: "aishamohdsheikh@gmail.com",
      phone: "09034650771",
    },
  },
  {
    fullname: "Godwin D. Kumknaba",
    description:
      "Agriprenuer | Advocate for better society | A teacher | A gospeller |",
    picture: require("./assets/faces/9.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "gdkums2020@gmail.com",
      phone: "09068602834",
    },
  },
  {
    fullname: "Isa Mohammed Umar (conjugate)",
    description: "networking and maintenance",
    picture: require("./assets/faces/10.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "yerimamaje@gmail.com",
      phone: "08064226296",
    },
  },
  {
    fullname: "Fatima Zara Abdulkadir",
    description: "a humanitarian",
    picture: require("./assets/faces/13.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "fateemahzahra001@gmail.com",
      phone: "08032732189",
    },
  },
  {
    fullname: "Rahmat Ismail Yusuf",
    description: "System Analyst",
    picture: require("./assets/faces/14.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "rahmatismail9@gmail.com",
      phone: "08142641424",
    },
  },
  {
    fullname: "Mohammed Bala Hammanjoda",
    description: "",
    picture: require("./assets/faces/15.jpg"),
    contact: {
      twitter: "https://twitter.com/Mb_Joda",
      linkedin: "",
      email: "Muhammadbalajoda@gmail.com",
      phone: "08142641605",
    },
  },
  {
    fullname: "Usi Heman Aliyu",
    description: "God First",
    picture: require("./assets/faces/16.jpg"),
    contact: {
      twitter: "https://twitter.com/UsihyeldaH",
      linkedin: "",
      email: "freemanu01@gmail.com",
      phone: "08108204012",
    },
  },
  {
    fullname: "Markus massa William",
    description: "",
    picture: require("./assets/faces/17.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "marcusmassawilliam@gmail.com",
      phone: "09091149332",
    },
  },
  {
    fullname: "Mustapha Usman",
    description:
      "A man with panaceas motive to debug his country's  higgledy-piggledy.",
    picture: require("./assets/faces/18.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "mustaphausmankarim@gmail.com",
      phone: "08024002777",
    },
  },
  {
    fullname: "Maisaratu Isa Kawu",
    description: "",
    picture: require("./assets/faces/19.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "maisaratisa@gmail.com",
      phone: "08062404162",
    },
  },
  {
    fullname: "ismail musa",
    description: "",
    picture: require("./assets/faces/20.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "babaldu715@gmail.com",
      phone: "08140697930",
    },
  },
  {
    fullname: "bashiru abubakar",
    description: "",
    picture: require("./assets/faces/21.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "bashirabubakar7@gmail.com",
      phone: "08136426932",
    },
  },
  {
    fullname: "Faisal mohammed girei",
    description: "",
    picture: require("./assets/faces/22.jpg"),
    contact: {
      twitter: "https://twitter.com/faisalgirei2",
      linkedin: "",
      email: "faisalmohammedgirei@gmail.com",
      phone: "08032390278",
    },
  },
  {
    fullname: "Abdullahi salihu bako",
    description: "",
    picture: require("./assets/faces/23.jpg"),
    contact: {
      twitter: "https://twitter.com/ibnsaleehu",
      linkedin: "",
      email: "absalbako@gmail.com",
      phone: "08036563522",
    },
  },
  {
    fullname: "Suwaiba ABDULLAHI",
    description: "Graphic designer",
    picture: require("./assets/faces/24.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "suwaibaabdullahi88@gmail.com",
      phone: "08060617566",
    },
  },
  {
    fullname: "Echin Bitrus Allurah",
    description: "jovial, inspiring and caring, ambition lecturing ",
    picture: require("./assets/faces/25.png"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "echinadashu@gmail.com",
      phone: "08062856423,08085950509",
    },
  },
  {
    fullname: "Mohammed Aminu saad ",
    description: "Auwal ICT Computer Analysts",
    picture: require("./assets/faces/26.jpg"),
    contact: {
      twitter: "https://twitter.com/Atoskey",
      linkedin: "",
      email: "atoskey1@gmail.com",
      phone: "08038026690,08025525932",
    },
  },
  {
    fullname: "Lamba B. Umar",
    description:
      "Simple and complicated. it is not How far you go in life but How well.",
    picture: require("./assets/faces/27.jpg"),
    contact: {
      twitter: "https://twitter.com/Lamborgrini080",
      linkedin: "linkedin.com/in/umar-lamba-951493216",
      email: "Lambaumar90@gmail.com ",
      phone: "08060405855,07019768005",
    },
  },
  {
    fullname: "simeon cedric",
    description: "",
    picture: require("./assets/faces/28.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "abelcedric27@gmail.com",
      phone: "08130151133",
    },
  },
  {
    fullname: "John Ali Machar",
    description: "Aspiring to become a world class IT practioner.",
    picture: require("./assets/faces/29.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "johnmachar4090@gmail.com",
      phone: "08143809047",
    },
  },
  {
    fullname: "SHAMSUDDEEN BELLO FURO",
    description: "",
    picture: require("./assets/faces/30.jpg"),
    contact: {
      twitter: "https://twitter.com/shamsuufuro",
      linkedin: "",
      email: "shamsuufuro@gmail.com",
      phone: "08032386682,07083348495",
    },
  },
  {
    fullname: "MUHAMMED ALI BUKAR",
    description: "",
    picture: require("./assets/faces/31.jpg"),
    contact: {
      twitter: "https://twitter.com/muhammed14",
      linkedin: "",
      email: "muhammadalibukar@gmail.com",
      phone: "08038114968",
    },
  },
  {
    fullname: "ABUBAKAR ISA",
    description: "",
    picture: require("./assets/faces/32.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "skudu2078@gmail.com",
      phone: "08165308284",
    },
  },
  {
    fullname: "SA'AD HARUNA",
    description: "",
    picture: require("./assets/faces/33.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "harunasaadmautech@gmail.com",
      phone: "08063646462",
    },
  },
  {
    fullname: "Ja'afar A yahyaa",
    description: "",
    picture: require("./assets/faces/34.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "yahyaajaafar@gmail.com",
      phone: "08064272729",
    },
  },
  {
    fullname: "Asma'u Halilu Yusuf",
    description: "Simple and humble",
    picture: require("./assets/faces/35.jpg"),
    contact: {
      twitter: "https://twitter.com/asmau555",
      linkedin: "LinkedIn.com/in/asmau-halilu-ob80271b1",
      email: "asmau.halilu555@gmail.com",
      phone: "08108044971,08121151397",
    },
  },
  {
    fullname: "Jamin Mafos",
    description: "A system networker, photographer ( multimedia)",
    picture: require("./assets/faces/36.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "mafosjamin@gmail.com",
      phone: "08134623784",
    },
  },
  {
    fullname: "JINOR JOEL NOMOR",
    description:
      "SATELLITE INSTALLER, AN ENTREPRENEUR, A SOCIALIST AND MC (MASTER OF CEREMONY).",
    picture: require("./assets/faces/37.png"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "jlnomor@gmail.com",
      phone: "08132325242",
    },
  },
  {
    fullname: "Abba Muhammad Musa",
    description: "I want to be a ICT promote r in my life",
    picture: require("./assets/faces/38.jpg"),
    contact: {
      twitter: "",
      linkedin: "https://www.linkedin.com/in/abba-mohammad-musa-7943b012a",
      email: "jlnomor@gmail.com",
      phone: "07031899358",
    },
  },
  {
    fullname: "Aliyu MB Umar",
    description: "",
    picture: require("./assets/faces/39.jpg"),
    contact: {
      twitter: "https://twitter.com/itz_emmbee",
      linkedin: "https://ng.linkedin.com/in/aliyu-mb-umar",
      email: "aliyumbumar@mautech.edu.ng",
      phone: "08035785828,08138823697",
    },
  },
  {
    fullname: "Peace Johnson Chinwendu",
    description: "",
    picture: require("./assets/faces/40.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "choicejohnson1998@gmail.com",
      phone: "07044545640",
    },
  },
  {
    fullname: "Alexander pwapedom",
    description: "",
    picture: require("./assets/faces/41.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "noemail",
      phone: "07064939323",
    },
  },
  {
    fullname: "Musa Umar",
    description: "",
    picture: require("./assets/faces/42.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "ribadu1994@gmail.com",
      phone: "08165102525",
    },
  },
  {
    fullname: "ALOYSIUS AUGUSTINE ELKANAH",
    description: "",
    picture: require("./assets/faces/43.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "augustinealoysius015@gmail.com",
      phone: "07060708171",
    },
  },
  {
    fullname: "Sunday sukanen",
    description: "",
    picture: require("./assets/faces/44.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "sundaysukanen4@gmail.com",
      phone: "08136202020",
    },
  },
  {
    fullname: "Abdullahi Anas Alfa",
    description:
      "simple, calm, aspiring to be in the big part of the tech world.",
    picture: require("./assets/faces/45.jpg"),
    contact: {
      twitter: "@anasalfa",
      linkedin: "",
      email: "anasabdullahi7@gmail.com",
      phone: "08137130380",
    },
  },
  {
    fullname: "Hassan B Galadima",
    description: "",
    picture: require("./assets/faces/46.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "hassanbgaladima@gmail.com",
      phone: "07064306457",
    },
  },
  {
    fullname: "Michael Collins",
    description: "An easy going friendly individual.",
    picture: require("./assets/faces/47.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "collinsbest2015@gmail.com",
      phone: "08106372656",
    },
  },
  {
    fullname: "Gambo Hamisu Adamu",
    description:
      "laziness is the secret ingredient that goes into failure, but it only kept a secret from the person who fails.",
    picture: require("./assets/faces/48.jpg"),
    contact: {
      twitter: "https://twitter.com/Khamizadamm",
      linkedin: "",
      email: "Khamizadamm@gmail.com",
      phone: "08065020250,08127952370",
    },
  },
  {
    fullname: "Farida Abdulkadir Bakari",
    description: "Fair in complexion,average height and calm.",
    picture: require("./assets/faces/49.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "faridaabdulkadir98@gmail.com",
      phone: "08034959017",
    },
  },
  {
    fullname: "Denis Dimas",
    description: "",
    picture: require("./assets/faces/50.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "dendim2265@gmail.com",
      phone: "07033998894",
    },
  },
  {
    fullname: "Tukur Rejoice Baraya ",
    description:
      "A goal driven person with a vision to build a successful career in IT",
    picture: require("./assets/faces/51.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "tukurrejoice@gmail.com",
      phone: "08130783632,08021119668",
    },
  },
  {
    fullname: "Akacha Charles",
    description: "",
    picture: require("./assets/faces/52.jpg"),
    contact: {
      twitter: "https://twitter.com/akacha_c/",
      linkedin: "https://www.linkedin.com/mwlite/in/akacha-joshua-a5a987206",
      email: "akachajoshua18@gmail.com",
      phone: "",
    },
  },
  {
    fullname: "Auwal Aminu",
    description: "",
    picture: require("./assets/faces/53.jpg"),
    contact: {
      twitter: "https://twitter.com/a_ameenu1",
      linkedin: "",
      email: "muhammadauwalaminu096@gmail.com",
      phone: "08064598694",
    },
  },
  {
    fullname: "Gaikara Jamimah James",
    description: "Business Tycoon",
    picture: require("./assets/faces/54.jpg"),
    contact: {
      twitter: "https://twitter.com/MeemahJames",
      linkedin: "",
      email: "jmeemah@gmail.com",
      phone: "08098394218,08069606167",
    },
  },
  {
    fullname: "Nazeerah aliyu Gama",
    description: "",
    picture: require("./assets/faces/55.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "gamanazira@gmail.com",
      phone: "08166566541",
    },
  },
  {
    fullname: "Dahiru Aliyu Adamu",
    description: "",
    picture: require("./assets/faces/56.jpg"),
    contact: {
      twitter: "https://twitter.com/Dahirualiyuada1",
      linkedin: "https://www.linkedin.com/in/dahiru-aliyu-8898a11b0",
      email: "dahirualiyuadamu@gmail.com",
      phone: "08146149773",
    },
  },
  {
    fullname: "Innocent Polycarp Bayero",
    description: "Handsome and Open Minded",
    picture: require("./assets/faces/57.jpg"),
    contact: {
      twitter: "https://twitter.com/real_ISaint Jr",
      linkedin: "",
      email: "innocentbayero1994@gmail.com",
      phone: "07037352351,07025087893",
    },
  },
  {
    fullname: "BAKOSHI DALUTA MUSA",
    description: "",
    picture: require("./assets/faces/58.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "dalutamusabakoshi81@gmail.com",
      phone: "08020779582",
    },
  },
  {
    fullname: "Fally Farnuwa Labaga",
    description: "",
    picture: require("./assets/faces/59.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "fallila222@gmail.com",
      phone: "09097016586",
    },
  },
  {
    fullname: "Rashida Abdullahi mamman",
    description: "networking",
    picture: require("./assets/faces/60.png"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "rashmeeabdullahi@gmail.com",
      phone: "08142074443",
    },
  },
  {
    fullname: "Steven turomale Harrison",
    description: "",
    picture: require("./assets/faces/steven.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "noemail",
      phone: "09065823322",
    },
  },
];
