const getRandomQuate = () => {
  const quotes = [
    //success quotes
    {
      quote:
        "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success.",
      source: "James Cameron",
      tag: "success",
    },
    {
      quote: "The Way Get Started Is To Quit Talking And Begin Doing",
      source: "Walt Disney",
      tag: "success",
    },
    {
      quote: "Don’t Let Yesterday Take Up Too Much Of Today.",
      source: "Will Rogers",
      tag: "success",
    },
    {
      quote: "We Generate Fears While We Sit. We Overcome Them By Action",
      source: "Dr. Henry Link",
      tag: "success",
    },

    //health quotes
    {
      quote:
        "Early to bed and early to rise, makes a man healthy wealthy and wise.",
      source: "Benjamin Franklin",
      tag: "health",
    },
    {
      quote: "Let food be thy medicine and medicine be thy food.",
      source: "Hippocrates",
      tag: "health",
    },
    {
      quote: "If you can’t pronounce it, don’t eat it.",
      source: "Common Sense",
      tag: "health",
    },
    {
      quote:
        "Health is like money, we never have a true idea of its value until we lose it.",
      source: "Josh Billings",
      tag: "health",
    },

    //spirituality quotes
    {
      quote: "Life is really simple, but men insist on making it complicated.",
      source: "Confucius",
      tag: "spirituality",
    },
    {
      quote: "My religion is very simple. My religion is kindness.",
      source: "Dalai Lama",
      tag: "spirituality",
    },
    {
      quote: "Knowing others is wisdom; knowing the self is enlightenment.",
      source: "Tao Te Ching",
      tag: "spirituality",
    },
    {
      quote:
        "When there is love in your heart, everything outside of you also becomes lovable.",
      source: "Veeresh",
      tag: "spirituality",
    },
  ];

  return quotes.splice(Math.floor(Math.random() * quotes.length), 1)[0].quote;
};

export default [
  {
    id: 1,
    fullname: "Dr. Bamanga Ribadu",
    description: "Head of Department",
    isStaff: true,
    picture: require("./assets/faces/hod.jpg"),
    contact: {
      twitter: "https://twitter.com/aiibrahim3",
      linkedin: "https://www.linkedin.com/in/abdulrasheed-ibrahim-2b3a90103/",
      email: "mb.ribadu@googlemail.com",
      phone: "07030076860",
    },
  },
  {
    id: 1,
    fullname: "Dr. Abdullahi Bashir",
    description: "Lecturer",
    isStaff: true,
    picture: require("./assets/faces/drbashir.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "noemail",
      phone: "08034315007",
    },
  },
  {
    id: 1,
    fullname: "Dr. Suleiman Saad",
    description: "Lecturer",
    isStaff: true,
    picture: require("./assets/faces/drsaad.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "noemail",
      phone: "08033516997",
    },
  },
  {
    id: 1,
    fullname: "Mr. Kabiru Ismail",
    description: "Lecturer",
    isStaff: true,
    picture: require("./assets/faces/kabir.jpg"),
    contact: {
      twitter: "https://www.linkedin.com/in/kabir-ismail-13172567/",
      linkedin: "https://www.linkedin.com/in/kabir-ismail-13172567/",
      email: "kabir.ismail@mautech.edu.ng",
      phone: "08069251514",
    },
  },
  {
    id: 1,
    fullname: "Mr. Abdulwahab Shehu",
    description: "Exam Officer",
    isStaff: true,
    picture: require("./assets/faces/exam.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "abdulwahabshehu25@gmail.com",
      phone: "08036989864",
    },
  },
  {
    id: 1,
    fullname: "Mr. Musa Jalo",
    description: "Lecturer",
    isStaff: true,
    picture: require("./assets/faces/jalo.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "abdulwahabshehu25@gmail.com",
      phone: "08022003330",
    },
  },
  {
    id: 1,
    fullname: "Mr. Hilary Watsilla",
    description: "Lecturer",
    isStaff: true,
    picture: require("./assets/faces/hillary.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "abdulwahabshehu25@gmail.com",
      phone: "08034749701",
    },
  },
  {
    fullname: "Shamsuddeen Sabiu A.K.A BiGtym MaMa...😎",
    description: getRandomQuate(),
    picture: require("./assets/faces/1.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "shamsuddeen600@gmail.com",
      phone: "09033884400",
    },
    address: "Wakili Buba B. Near Transformer Mayo Belwa Adamawa State",
    hobbies: "Travelling, Reading, and Watching Movies.",
    goodwillMessage:
      "Our dearest teachers thank you for being very kind and patient and also for being a role model to us. Respect for you will remain in our heart forever. \nThank you for everything. \nHappy Graduation NAITS❤ Class of 2021.",
  },
  {
    fullname: "MUBARAK IBRAHIM GAMBO",
    description: getRandomQuate(),
    picture: require("./assets/faces/2.jpeg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "JIMETA YOLA",
    hobbies: "Chatting and reading books",
    goodwillMessage: "success",
  },
  {
    fullname: "Marngayu Blessing Bello",
    description: getRandomQuate(),
    picture: require("./assets/faces/3.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "Specialist hospital quarters, Yola",
    hobbies: "Reading, exploring new ideas.",
    goodwillMessage:
      "Diligence and consistency is the secret to success, may the Lord bless us in all our endeavors, I love you all my IMT family.",
  },
  {
    fullname: "Umar Abubakar",
    description: getRandomQuate(),
    picture: require("./assets/faces/4.jpeg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "N0 153 Abuja Road Yola South",
    hobbies: "Footballer.",
    goodwillMessage: "NEVER FORGET NAITS FAMILY 👪",
  },
  {
    fullname: "BigBasha",
    description: getRandomQuate(),
    picture: require("./assets/faces/5.png"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "08036423805",
    },
    address: "",
    hobbies: "Footballer.",
    goodwillMessage:
      "What a pity! I'm not at your place! \nMiles separate me from you, Success guys all d way, miss u so much.",
  },
  {
    fullname: "Isaac Yakubu Dadu ",
    description: getRandomQuate(),
    picture: require("./assets/faces/6.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "C/O Low Cost Primary school Uba, Askira/Uba LGA, Borno State ",
    hobbies: "Football, Researching and Reading.",
    goodwillMessage:
      "We are Great Family of NAITS and forever great we will remain. I wish everyone success in every endeavor of life.",
  },
  {
    fullname: "George Joseph fayo",
    description: getRandomQuate(),
    picture: require("./assets/faces/7.jpeg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "NUMAN",
    hobbies: "Reading.",
    goodwillMessage: "The Good lord will see us through",
  },
  {
    fullname: "MUHAMMAD GIDADO MUHAMMAD ",
    description: getRandomQuate(),
    picture: require("./assets/faces/8.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "35 ALKASUM STREET YOLA TOWN",
    hobbies: "PROGRAMMING",
    goodwillMessage: "Be a Good Example...",
  },
  {
    fullname: "HARUNA HAMMADU",
    description: getRandomQuate(),
    picture: require("./assets/faces/9.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "PARIYA WARD FUFORE LGA. ADAMAWA STATE.",
    hobbies: "READING AND WRITING",
    goodwillMessage:
      "Don't quit trying and don't rest until you have achieve all you've been ever dream of. Let us keep doing greater things in future that will make us proud. Congratulations to all of us on our graduation. \nHappy Graduation NAITS Family. Class of 2021.",
  },
  {
    fullname: "Christopher Williams",
    description: getRandomQuate(),
    picture: require("./assets/faces/10.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "Yelwa Ward Mubi North Adamawa state",
    hobbies: "Designing and programming.",
    goodwillMessage: "LET'S MEET IN HIGH PLACES ",
  },
  {
    fullname: "Musa Saleh 'ATTACHEE'",
    description: getRandomQuate(),
    picture: require("./assets/faces/11.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "musaattachee@gmail.com",
      phone: "",
    },
    address: "No. 57 Rabeh Street, Bako Ward Yola Town ",
    hobbies: "Research.",
    goodwillMessage: "Am missing my course mates class of 2021, Love You All.",
  },
  {
    fullname: "Umar faruk umar",
    description: getRandomQuate(),
    picture: require("./assets/faces/92.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "No 38 ribadu road fufore LG",
    hobbies: "Reading and chatting ",
    goodwillMessage:
      "We pray the success from Allah, may we go higher to the highest level. \nMay Allah forgive my dad and grant him jannatul firdaus 🙏",
  },
  {
    fullname: "Ahmed Manu Gidado",
    description: getRandomQuate(),
    picture: require("./assets/faces/12.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "Shelleng ",
    hobbies: "Salawat ala Sayyidil wujud",
    goodwillMessage:
      "Thank you guys for your patience and dedication God bless you all🙏🙏🙏 \nMay Almighty Allah fulfill our dreams.",
  },
  {
    fullname: " Abdulmumini Kawuji ' AbdullSunnah'",
    description: getRandomQuate(),
    picture: require("./assets/faces/13.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "Adamawa State Yola North Rumde Ward Doubeli Jummat Mosque",
    hobbies: "Watching Football and Playing Football",
    goodwillMessage:
      "Alhamdullah, Masha Allah, I am really proud of our Class of 2022, We work so hard every day to achieve this accomplishment, very incredible success, Best of luck on our new beginnings!",
  },
  {
    fullname: "Ahudurhyel Francis",
    description: getRandomQuate(),
    picture: require("./assets/faces/14.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "09063325384",
    },
    address: "Opposite EYN church Zhediyi, Hong",
    hobbies: "Singing",
    goodwillMessage:
      "No matter how hard life has been on you, never give up on God because He has a plan for you.",
  },
  {
    fullname: "Jamila Jibril ",
    description: getRandomQuate(),
    picture: require("./assets/faces/15.jpeg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "08035139019",
    },
    address: "",
    hobbies: "Eating, dancing and Sleeping ",
    goodwillMessage:
      "Let your heart be the most beautiful thing about you, be Kind 🤍",
  },
  {
    fullname: "Agbaji Adadu Samuel ",
    description: getRandomQuate(),
    picture: require("./assets/faces/16.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "08146713241",
    },
    address: "",
    hobbies: "Footballer.",
    goodwillMessage: "Success",
  },
  {
    fullname: "Mordecai Suleiman Bobbo",
    description: getRandomQuate(),
    picture: require("./assets/faces/17.jpeg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "Wuro Patuji Primary School ",
    hobbies: "Music",
    goodwillMessage: "Making more money",
  },
  {
    fullname: "UMAR YUNUSA",
    description: getRandomQuate(),
    picture: require("./assets/faces/18.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "Yola Town.",
    hobbies: "Arguing with people online.",
    goodwillMessage: "Step Up And Be Brave. Good Luck.",
  },
  {
    fullname: "Shamsudeen Suleiman",
    description: getRandomQuate(),
    picture: require("./assets/faces/19.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "Lelewalji, Yola South, Adamawa State. ",
    hobbies: "Playing Video Games and Reading Books(online)",
    goodwillMessage: "ALHAMDULILLAH ALAA KULLI HALI",
  },
  {
    fullname: "Mustapha Badisha",
    description: getRandomQuate(),
    picture: require("./assets/faces/20.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "mustaphabadisha@gmail.com",
      phone: "",
    },
    address: "",
    hobbies: "Thinks 3 out 4 of my life.",
    goodwillMessage:
      "Take a break from your computer my fellow developers. Go out, take a walk and clear your head. We all have our crucibles. ",
  },
  {
    fullname: "Abduljalil Jaafar ",
    description: getRandomQuate(),
    picture: require("./assets/faces/21.jpeg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "No 22 Sarkin Dawaki ward jalingo",
    hobbies: "Reading, Football,",
    goodwillMessage:
      "We are Moving on to a new and exciting chapter in our life. I wish You all the best for the Future that lies ahead. \nCongratulations to y’all Naits Family on your graduation ",
  },
  {
    fullname: "Patience A Reuben",
    description: getRandomQuate(),
    picture: require("./assets/faces/22.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "Karewa extension ",
    hobbies: "Cooking ",
    goodwillMessage: "One love keep us together ",
  },
  {
    fullname: "Bilyaminu Jibrilla",
    description: getRandomQuate(),
    picture: require("./assets/faces/23.jpeg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "Belel ward Maiha LGA, Adamawa State",
    hobbies: "Support",
    goodwillMessage:
      "May God bless our lives and fulfill everyone's wishes for good",
  },
  {
    fullname: "Zubairu Umar",
    description: getRandomQuate(),
    picture: require("./assets/faces/24.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "Wuro Hausa Girei II Ward Girei LGA \nAdamawa State Nigeria ",
    hobbies: "Research and traveling ",
    goodwillMessage:
      "Wishing all the Graduating Students of Modibbo Adama University Yola,Success in their future endeavors wherever they are.",
  },
  {
    fullname: "Bobby Sambo Bobga",
    description: getRandomQuate(),
    picture: require("./assets/faces/25.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "No6 sarkin kudu street jimeta yola ",
    hobbies: "Reading and watching football ",
    goodwillMessage:
      "To All My Course mates, \nWith immense pride, I congratulate my dear students on a job well done. Having gotten to know you over the last few years has enriched my life. I know you will go out into the world with confidence in your abilities to communicate and analyze the world you encounter. Remember, you can always reach out to me for counsel. With faith that you will affect great change in the world, I wish you the best of luck. \nStay in Touch, \nBOBBY SAMBO BOBGA ",
  },
  {
    fullname: "Wakumahyel Joseph",
    description: getRandomQuate(),
    picture: require("./assets/faces/26.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "Biu, Borno state",
    hobbies: "Chatting and listening to music",
    goodwillMessage:
      "Always have it in mind that life is short, so do the right thing and stay in peace with everyone.🙏🤗",
  },
  {
    fullname: "Zainab Bakari Ahmed",
    description: getRandomQuate(),
    picture: require("./assets/faces/27.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "No 97 Abuja Road, Yola Town Adamawa State ",
    hobbies: "Reading ",
    goodwillMessage: "wish us all success in life",
  },
  {
    fullname: "EMMANUEL UCHE",
    description: getRandomQuate(),
    picture: require("./assets/faces/28.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address:
      "KOFARE OFF MBACHURE ROAD BEHIND AGRIC MECHANIZATION HEAD QUARTERS. YOLA NORTH",
    hobbies: "FOOTBALL AND READING",
    goodwillMessage:
      "My graduation celebrations will not be complete until I thank you all for being such a supportive classmates  to me…. Thanks a lot for being there",
  },
  {
    fullname: "Unity Habila",
    description: getRandomQuate(),
    picture: require("./assets/faces/29.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "Former Hossana academy Sangere futy",
    hobbies: "Football, Networking & reading",
    goodwillMessage:
      "With friends we succeed, with enemies we become more successful. ( no one can make you interior without your conscious).",
  },
  {
    fullname: "Adasu yakubu Alkali",
    description: getRandomQuate(),
    picture: require("./assets/faces/30.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "08069809130",
    },
    address: "",
    hobbies: "Reading, watching movie and listening to music ",
    goodwillMessage:
      "When I think of any of my successes, I am thankful to God from whom all blessings flow and to my family and friends who enrich my life big thanks to everyone I love you all cheers!",
  },
  {
    fullname: "Mohammed Bamanga Gidado",
    description: getRandomQuate(),
    picture: require("./assets/faces/31.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "Tudun wada",
    hobbies: "Reading",
    goodwillMessage: "May Allah make us to succeed in our future",
  },
  {
    fullname: "Hassana Abubakar Hassan ",
    description: getRandomQuate(),
    picture: require("./assets/faces/32.jpeg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "08140141800",
    },
    address: "",
    hobbies: "Cooking, listening to music.",
    goodwillMessage: "Be the change you wish to see in the world.",
  },
  {
    fullname: "Ibrahim Jalo ",
    description: getRandomQuate(),
    picture: require("./assets/faces/33.jpeg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "08124267472",
    },
    address: "",
    hobbies: "Smiling ",
    goodwillMessage: "GOD BLESS NAITS FAMILY ",
  },
  {
    fullname: "Mabendi Zira Yusuf",
    description: getRandomQuate(),
    picture: require("./assets/faces/34.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address:
      "Mabendi Tech Computer Center Anguwan Fulani Hayin Gada Vunoklang, Girei Lga",
    hobbies: "Teaching and Research",
    goodwillMessage:
      "Let this love follow us as we are leaving this environment. Naits One Love, One family. Together we stand!",
  },
  {
    fullname: "Abdulmumini Abba Maje",
    description: getRandomQuate(),
    picture: require("./assets/faces/35.png"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "No2 Maje street Rogo Ward Takum Taraba State Nigeria",
    hobbies:
      "Politics, Meeting New people, I love Patriots Citizens of Nigeria",
    goodwillMessage:
      "God bless aus all (Allah ya Sadamu da Alkhairi, Inna Mana Fatan Alkhairi) Ameen!!",
  },
  {
    fullname: "Shamsiya Abubakar",
    description: getRandomQuate(),
    picture: require("./assets/faces/36.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "Jereng Mayo/Belwa Adamawa state",
    hobbies: "Cooking, Traveling",
    goodwillMessage:
      "Congratulations to all us may we leave long to enjoy the fruits of our labour, hustle oooo and keep it legit, remember you don't have a name until you make one for yourself, I wish us all the best. \n#MissChubby",
  },
  {
    fullname: "Sheriff, Tadegopwa",
    description: getRandomQuate(),
    picture: require("./assets/faces/37.png"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "07068706056",
    },
    address: "Adjacent to FARO Company, Kofare Industrial Layout.Jimeta/Yola",
    hobbies: "Listening to music and Football",
    goodwillMessage:
      "I thank God for making me fulfill this chapter of my life together with this beautiful family (NAITS), I'm really proud of this class of 2021, and I can't wait to see all your accomplishments in the nearest future. God bless you all.",
  },
  {
    fullname: "Halima Muhammad Nasir ",
    description: getRandomQuate(),
    picture: require("./assets/faces/38.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "0803679188",
    },
    address: "",
    hobbies: "Fashion designer and cooking ",
    goodwillMessage:
      "I wish for all of us a successful feature ahead, may Almighty Allah guide and protect us from the evil eye and may Aljannatul Firdausi be last destination Ameeeennn ....",
  },
  {
    fullname: "RUFA'EE AMINU ",
    description: getRandomQuate(),
    picture: require("./assets/faces/39.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "rufaity2@gmail.com",
      phone: "08083706270",
    },
    address: "Nguroje Sardauna LGA Taraba State, Phone Number",
    hobbies: "Reading, Playing Music, Traveling ",
    goodwillMessage:
      "It is not in the stars to hold our destiny but in ourselves, If you can imagine it, you can achieve it, if you can dream it, you can become it. Happy Graduation.🎓 \nNAITS family..❤ Class of 2021",
  },
  {
    fullname: "Samuel Ishaya ",
    description: getRandomQuate(),
    picture: require("./assets/faces/95.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "Wauru jabbe, Yola",
    hobbies: "Chess, Music, reading  and football",
    goodwillMessage:
      "I pray for my classmates and myself success after graduation ",
  },
  {
    fullname: "Bassi Garba ",
    description: getRandomQuate(),
    picture: require("./assets/faces/40.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "Federal housing estate phase3 ",
    hobbies: "Singing",
    goodwillMessage:
      "As  we graduate I pray for favor our there. Let the love that has been keeping us keep burning. I love you all NAITS. Gboss Cares.",
  },
  {
    fullname: "Jamila Mohammed",
    description: getRandomQuate(),
    picture: require("./assets/faces/41.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "No.10 Lamido Street Shagari Phase one Yola South ",
    hobbies: "Cooking, reading, and listing to music ",
    goodwillMessage:
      "May Almighty Allah bless our hustle and my he see us through this life.",
  },
  {
    fullname: "Kanane Jones Sukanebe",
    description: getRandomQuate(),
    picture: require("./assets/faces/98.jpeg"),
    contact: {
      twitter: "https://web.facebook.com/profile.php?id=100070083510585",
      linkedin: "https://web.facebook.com/profile.php?id=100070083510585",
      email: "",
      phone: "08030541337",
    },
    address: "Yola, Nigeria",
    hobbies: "Cooking, Conversing, and Travelling",
    goodwillMessage: "",
  },
  {
    fullname: "ATIKU ABUBAKAR",
    description: getRandomQuate(),
    picture: require("./assets/faces/42.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "Opp. No 20 Ribadu Street, Yola South",
    hobbies: "Reading and Learning New Things",
    goodwillMessage:
      "Verily after every hardship there is relief, after every hardship there is relief",
  },
  {
    fullname: "Nusaiba Muhammad girei ",
    description: getRandomQuate(),
    picture: require("./assets/faces/43.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "No 2 baissa Street nepa road ",
    hobbies: "Reading and watching movies ",
    goodwillMessage:
      "keep doing good things and you will see the good result,with Allah everything gonna be alright,I wish us success in life,",
  },
  {
    fullname: "Usman Bayero Kumo",
    description: getRandomQuate(),
    picture: require("./assets/faces/44.png"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "Bakoshi Street S/Yaki Quarters Kumo",
    hobbies: "Reading and smiling.",
    goodwillMessage: "Allah is great..",
  },
  {
    fullname: "Sudakumtemi Johnson",
    description: getRandomQuate(),
    picture: require("./assets/faces/45.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address:
      "Gangdu State Dev. Area, Yelwa Timdore Distr, Ganye LGA Adamawa state",
    hobbies: "Reading, Praying, Playing instruments and Singing",
    goodwillMessage:
      " You've been very inspiring, considerate, caring, supportive, and trusting friends. I want to use this moment to thank you deeply for everything I'm grateful to you all my Lecturers and my colleagues",
  },
  {
    fullname: "Simon john",
    description: getRandomQuate(),
    picture: require("./assets/faces/81.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "Maiduguri Borno state polo",
    hobbies: "Reading and coding ",
    goodwillMessage:
      "We all are human we ought to respect and value each other's opinion no one is born perfect",
  },
  {
    fullname: "Andrew Abel Gabriel",
    description: getRandomQuate(),
    picture: require("./assets/faces/46.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "08131201332",
    },
    address: "Kofare,c/o Chuks Block Industry, Jimeta/Yola",
    hobbies: "Watching movies, Reading",
    goodwillMessage:
      "Congratulations to of us the Class of 2021 on our graduation. All of our hard work and perseverance have led us to this proud moment in our lives. Best wishes on our next adventure!",
  },
  {
    fullname: "ALIYU MAINA",
    description: getRandomQuate(),
    picture: require("./assets/faces/47.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "SANGERE FUTY, GIREI LGA, ADAMAWA STATE",
    hobbies: "USING COMPUTER",
    goodwillMessage: "MAY GOD CONTINUE TO HELP US ",
  },
  {
    fullname: "Abdulaziz abubakar michika ",
    description: getRandomQuate(),
    picture: require("./assets/faces/48.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: " 08142177980 ",
    },
    address: "Michika opposite INEC office michika local government adamawa",
    hobbies: "Data entry, programmer, marketer and entrepreneur ",
    goodwillMessage: "With almighty Allah everything is possible ",
  },
  {
    fullname: "Joshua Abraham Amos ",
    description: getRandomQuate(),
    picture: require("./assets/faces/49.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "COAS BLOCK A, FLAT 7, YAR'ADUA BARRACKS, ASOKORO, ABUJA.",
    hobbies: "Watching Movies and Listening to Music ",
    goodwillMessage:
      "We have a great class of 2021, and I can't wait to read about all your successes in the coming chapter. On your graduation, Class of 2021, congratulations. You have earned this proud moment in your lives with your dedication and perseverance. Wishing you luck on your upcoming Adventure!",
  },
  {
    fullname: "David James Birdling",
    description: getRandomQuate(),
    picture: require("./assets/faces/50.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "Karewa Extension",
    hobbies: "playing soccer,reading novels and traveling",
    goodwillMessage:
      "Farewell to the most amazing class ever. I will for ever miss this remarkable institute  dearly. May we all be victorious in all spheres of life!......Farewell my amazing people.",
  },
  {
    fullname: "Yusuf Njidda ",
    description: getRandomQuate(),
    picture: require("./assets/faces/51.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "Off Yola Bye -Pass Yola South ",
    hobbies: "Traveling and Research ",
    goodwillMessage: "Glory be Allah for infinite Mercy all through. ",
  },
  {
    fullname: "Haruna Bulus",
    description: getRandomQuate(),
    picture: require("./assets/faces/52.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "Gombe",
    hobbies: "Football",
    goodwillMessage: "Ba mai yi sai Allah",
  },
  {
    fullname: "Onyinye precious okonkwo ",
    description: getRandomQuate(),
    picture: require("./assets/faces/53.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "No42 Demsawo street jimeta Yola ",
    hobbies: "Travelling and business ",
    goodwillMessage: "Success and breakthrough to everyone ",
  },
  {
    fullname: "Racheal Tabakiya",
    description: getRandomQuate(),
    picture: require("./assets/faces/54.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "Gboko, new GRA benue state.",
    hobbies: "Singing, dancing, reading, Cooking, hangout.",
    goodwillMessage:
      "I wish everyone the very best that life has to offer and a happy ending, one love❤️ ",
  },
  {
    fullname: "Solomon yakubu Dakkus",
    description: getRandomQuate(),
    picture: require("./assets/faces/55.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "Specialist quarters jimeta/yola",
    hobbies: "Traveling & Listening to music",
    goodwillMessage:
      "It's wonderful to be one of NAITs FAM class of 2021 \nwith people as nice as you guys - You Guys made Me feel so at home by everything you do. So this just comes to thank you all in a warm and special way- For your kind supports in one way or the other was enjoyed much more than words can say! \nMore Luv, Less Ego FAM (LetLoveLead)",
  },
  {
    fullname: "Hussaina Muhammad sani",
    description: getRandomQuate(),
    picture: require("./assets/faces/56.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "Abuja road yola Town",
    hobbies: "Reading, music, outing",
    goodwillMessage:
      "All praise is to Almighty Allah who gave me the grace and privilege to have a successful end. Congratulations to us on our graduation. I cannot wait to see All our accomplishments in the next chapter.",
  },
  {
    fullname: "Hauwa Musa",
    description: getRandomQuate(),
    picture: require("./assets/faces/57.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "08145644926",
    },
    address: "",
    hobbies: "Travelling",
    goodwillMessage:
      "Delayed but not denied! The world is there waiting for our potentials. CONGRATULATIONS GREAT NAITS!!!",
  },
  {
    fullname: "Ishaya bulus",
    description: getRandomQuate(),
    picture: require("./assets/faces/58.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "Jambutu by-pass jimeta",
    hobbies: "Discovery, sport",
    goodwillMessage: "Better dayz ahead to all my colleages",
  },
  {
    fullname: "Ahmed Mubarak",
    description: getRandomQuate(),
    picture: require("./assets/faces/59.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "Damare yola south",
    hobbies: "Reading",
    goodwillMessage: "A.K.A Kawu",
  },
  {
    fullname: "Gabriel Blessing",
    description: getRandomQuate(),
    picture: require("./assets/faces/60.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "No.  113 Mubi Road Jimeta ",
    hobbies: "Cooking and Singing",
    goodwillMessage:
      "It is not of him that willth but it is of God who shows Mercy. I love you all!",
  },
  {
    fullname: "MUNYAL DRAMBI ",
    description: getRandomQuate(),
    picture: require("./assets/faces/61.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "Michika II ward, Michika local Government Area Adamawa State",
    hobbies: "Reading and Socialism",
    goodwillMessage:
      "As we come to end of our academic journey as graduates, my prayer towards everyone is well leaving and success the new environment.",
  },
  {
    fullname: "Peter joshua",
    description: getRandomQuate(),
    picture: require("./assets/faces/62.png"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "07041218673, 07046889092",
    },
    address: "",
    hobbies: "Reading,  listening to music and playing Plano ",
    goodwillMessage:
      "So i finally made it through the mill! I know just how it feels. ",
  },
  {
    fullname: "Annah Nashon Gubi",
    description: getRandomQuate(),
    picture: require("./assets/faces/82.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "09039250502",
    },
    address: "",
    hobbies: "Watching movies/chatting ",
    goodwillMessage:
      "Learning is the only thing the mind never exhausts,never fears and never regrets.",
  },
  {
    fullname: "Christiana Ezekiel ",
    description: getRandomQuate(),
    picture: require("./assets/faces/83.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "07033531298",
    },
    address: "Numan Road wuro jabbe",
    hobbies: "Reading, singing and chilling ",
    goodwillMessage:
      "I appreciate God,the maker of heaven and earth,the alpha and Omega,the beginning and earth,for giving me the grace and privilege to have a successful end throughout my studies.",
  },
  {
    fullname: "Yahya Alim",
    description: getRandomQuate(),
    picture: require("./assets/faces/93.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "yahayaalim47@gmail.com",
      phone: "08083034764",
    },
    address: "Bungel, Belel district Maiha LGA",
    hobbies: "Watching movies and reading",
    goodwillMessage: "May all our Insha Allah turn to Alhmdulillah",
  },
  {
    fullname: "Nanah Ibrahim",
    description: getRandomQuate(),
    picture: require("./assets/faces/63.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "Wauru jabbe",
    hobbies: "Reading and Cooking",
    goodwillMessage: "Congratulations on our new beginning",
  },
  {
    fullname: "Salihu Abdullahi Digil",
    description: getRandomQuate(),
    picture: require("./assets/faces/64.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "153 Base Service Group NAF Base Yola",
    hobbies: "Swimming",
    goodwillMessage:
      "I may say goodbye to you, but my heart will never say goodbye. I will always keep you in my heart. I wish us all a successful future, farewell.",
  },
  {
    fullname: "Seun Fabusola",
    description: getRandomQuate(),
    picture: require("./assets/faces/84.jpeg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "Jambutu",
    hobbies: "Sleeping, eating, traveling ",
    goodwillMessage: "Gods time is the best",
  },
  {
    fullname: "Solomon Sabo",
    description: getRandomQuate(),
    picture: require("./assets/faces/65.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "07038664668",
    },
    address: "Demsawo,  Adamawa state Nigeria ",
    hobbies: "Making arts,  watching,  chatting ",
    goodwillMessage:
      "What you think,  you attract. Think good for yourself and hope for the best.  6 years with you all was memory #ROI",
  },
  {
    fullname: "Moallahyidi Ahmed",
    description: getRandomQuate(),
    picture: require("./assets/faces/85.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "Opposite madam Tina store kasuwan bohu jimeta yola ",
    hobbies: "Traveling",
    goodwillMessage: "Tell we meet again",
  },
  {
    fullname: "Safiya Abdulhamid Arabo",
    description: getRandomQuate(),
    picture: require("./assets/faces/66.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "Karewa maskare Behind Hotel la birem ",
    hobbies: "Cooking,Gardening and Travelling,",
    goodwillMessage:
      "All of our hard work and perseverance have led us to this proud moment in our lives. ",
  },
  {
    fullname: "Ruth Bitrus",
    description: getRandomQuate(),
    picture: require("./assets/faces/67.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "'09030986868",
    },
    address: "",
    hobbies: "Listening to music",
    goodwillMessage: "Wish you all success",
  },
  {
    fullname: "Usman Ab",
    description: getRandomQuate(),
    picture: require("./assets/faces/68.jpeg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "Maitama AbJ",
    hobbies: "Dancing ",
    goodwillMessage: "Favor awaits everyone of us",
  },
  {
    fullname: "Zubairu Umar ",
    description: getRandomQuate(),
    picture: require("./assets/faces/69.png"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "Wuro Hausa Girei II Ward Girei LGA Adamawa State ",
    hobbies: "Research and Traveling ",
    goodwillMessage:
      "Wishing all the Final Year students of all Nigerian universities success in their Exams",
  },
  {
    fullname: "Joy Solomon Durkwa",
    description: getRandomQuate(),
    picture: require("./assets/faces/96.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "08107986760",
    },
    address: "",
    hobbies: "Singing, watching movies",
    goodwillMessage: "The best is yet to come... grateful heart",
  },
  {
    fullname: "Hapsat mahmud Tuta",
    description: getRandomQuate(),
    picture: require("./assets/faces/70.jpeg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "No 40 Abuja road sanda",
    hobbies: "Trying new recipes and Watching movie ohhh and sleeping ",
    goodwillMessage:
      "Always be true to yourself don’t pretend to be someone who you are not.",
  },
  {
    fullname: "ABUBAKAR ABBA UMAR",
    description: getRandomQuate(),
    picture: require("./assets/faces/71.jpeg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "No 33 AI STREET DOCTORS QTRS YOLA TOWN",
    hobbies: "FOOTBALL,MUSIC,SLEEPING,AND MOVIES",
    goodwillMessage: "There is no such thing as an Ugly billionaire",
  },
  {
    fullname: "KAREEM MOJEED ADEBOLA",
    description: getRandomQuate(),
    picture: require("./assets/faces/72.jpeg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "IJANIKIN, LAGOS",
    hobbies: "Resting, Watching Football and Movies.",
    goodwillMessage: "Hustle until you no longer need to introduce yourself ",
  },
  {
    fullname: "Danjuma Adamu Mshelia",
    description: getRandomQuate(),
    picture: require("./assets/faces/73.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "Gwandzang Hawul L.G.A Borno State",
    hobbies: "Footballer",
    goodwillMessage: "We will continue to be together for ever and ever.",
  },
  {
    fullname: "Auwal Musa Hassan",
    description: getRandomQuate(),
    picture: require("./assets/faces/74.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "08061244254",
    },
    address: "",
    hobbies: "Traveling /////",
    goodwillMessage:
      "No doubt, Allah is the best planner indeed. Whatever we plan or think for our life, only that will happen that Allah planned.",
  },
  {
    fullname: "NIGODAN ARKE MUSA ",
    description: getRandomQuate(),
    picture: require("./assets/faces/91.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "07039725622",
    },
    address: "Song local government ",
    hobbies: "Traveling and Reading ",
    goodwillMessage: "What Goes up will surely come down ",
  },
  {
    fullname: "Valentine Friday Garba",
    description: getRandomQuate(),
    picture: require("./assets/faces/94.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "08130299576",
    },
    address: "No 35 hospital road jimeta Yola",
    hobbies: "Watching football and playing football and listening to music ",
    goodwillMessage:
      "Success in everything we do in life,and may our labour never be in vain.",
  },
  {
    fullname: "Fatima Abubakar",
    description: getRandomQuate(),
    picture: require("./assets/faces/75.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "38 Ahmadu Bello way jimeta",
    hobbies: "Reading and traveling",
    goodwillMessage: "We did it !Alhamdullillah",
  },
  {
    fullname: "Arabi M. Abdullahi",
    description: getRandomQuate(),
    picture: require("./assets/faces/86.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "Off nepa road j/yola no. 17 Jen close",
    hobbies: "Reading and Football",
    goodwillMessage:
      "Success is not a product of coincidence is a product of yesterday's planning and hard work. This is your time to plan for your next product.",
  },
  {
    fullname: "Abubakar Salihu ",
    description: getRandomQuate(),
    picture: require("./assets/faces/87.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "Yola town ",
    hobbies: "Sports and tourism ",
    goodwillMessage: "Wishing all of us a success after university ",
  },
  {
    fullname: "IMRAN USMAN",
    description: getRandomQuate(),
    picture: require("./assets/faces/76.jpeg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "Block 21 Flat 7 , CBN QUATERS BEHIND OANDO GARKI ABUJA",
    hobbies: "Listening to Music ",
    goodwillMessage:
      "Erhhhmmm I want use this medium to appreciate each and everyone of you, I’ve learnt alot from you guys some directly some indirectly, It has been a long rough journey for us all but at last we overcome  \nMay we all achieve great things in our future endeavors 💚 \nThank you for the lessons I really appreciate and lots of LOVE from here!",
  },
  {
    fullname: "Bonidefaiye Friday Dayo",
    description: getRandomQuate(),
    picture: require("./assets/faces/77.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "No 68B Aiyeteju Street Kabba, Kogi State",
    hobbies: "Reading, Handball and Traveling",
    goodwillMessage:
      "I bring goodwill message to all final year Information Technology department, you have been such an amazing fellow all this years from 100L to 500L, I am to delight and happy I met you all on our way to attaining this milestone in our life. I wish you all success and greatness in all ur future endeavours!! You shall livelong to fulfil your God's purpose for your life. \nGod bless all Final Year \nGod bless Information Technology Department \nGod bless MAU",
  },
  {
    fullname: "Amedu Martins Urah",
    description: getRandomQuate(),
    picture: require("./assets/faces/78.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "08037020217, 08020802192.",
    },
    address: "",
    hobbies: "Eating",
    goodwillMessage: "Live like there is no tomorrow ",
  },
  {
    fullname: "Ngati Nelson",
    description: getRandomQuate(),
    picture: require("./assets/faces/88.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "Kofare Agric along Zone 3",
    hobbies: "Getting Money and Spending it Well",
    goodwillMessage:
      "Life is not beds of Roses. \nSo Live Smart and Shine your Eyes. \nThe journey ahead is Greater and Tougher. \nBUT Through Perseverance and Hardwork \nAll good must come to a Halt. \nUp NAITS",
  },
  {
    fullname: "Mustapha Abubakar",
    description: getRandomQuate(),
    picture: require("./assets/faces/79.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "Tudun Wada Shamaki Ward, Near GSTC Gombe, Gombe State.",
    hobbies: "Recitation of the Holy Qur'an and watching movies.",
    goodwillMessage:
      "My dear respected colleagues,  \nMartin Luther King junior once said that 'Coming together is the beginning, keeping together is the progress and working together is the success thus i must say that haven seeing ourselves to the end of this particular journey is a story worth sharing, our departure isn't a reason to forget ourselves, let's be with one another always in our heart please, I promise to represent myself, to represent you and to represent the institution that mastermind what we've become together and also protect and promote the right and previledge of all of you my dear brothers and sisters. \nMay success and glory continue to be in our portion. \nThank you all.",
  },
  {
    fullname: "Anas Bakari Ahmed",
    description: getRandomQuate(),
    picture: require("./assets/faces/80.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "",
      phone: "",
    },
    address: "No.97 Lamido Sanda Road",
    hobbies: "Reading and Playing",
    goodwillMessage: "Alhamdulillah",
  },
  {
    fullname: "hamidu hassan",
    description: getRandomQuate(),
    picture: require("./assets/faces/89.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "hamiduhassan202@gmail.com",
      phone: "08022692974",
    },
    address: "mansur Quaters gembu",
    hobbies: "football",
    goodwillMessage: "Alhamdulillah Alhamdulillah Alhamdulillah",
  },
  {
    fullname: "musa maina dauda",
    description: getRandomQuate(),
    picture: require("./assets/faces/90.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "musamainaam20@gmail.com",
      phone: "07019947735 08145414279",
    },
    address: "Biu borno state behind motor park, dauda terror street",
    hobbies: "Tea, football, games",
    goodwillMessage:
      "Best of luck at your race tomorrow!... \nGood luck today!... \nGood luck and good wishes. \nAll the luck in the world All wish for you.",
  },
  {
    fullname: "Maryam Bakari",
    description: getRandomQuate(),
    picture: require("./assets/faces/97.jpg"),
    contact: {
      twitter: "",
      linkedin: "",
      email: "maryamabubakar1908@gmail.com",
      phone: "07019947735 08145414279",
    },
    address: "Bauchi street Jimeta Yola",
    hobbies: "Tea, football, games",
    goodwillMessage:
      "Best of luck at your race tomorrow!... \nGood luck today!... \nGood luck and good wishes. \nAll the luck in the world All wish for you.",
  },
];
